[package]
name = "caster"
description = "Stay tuned."
version = "0.0.1"
edition = "2021"
license = "MIT"


[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
pretty_env_logger = "0.4"